globalConfig:
  prometheus_url: http://prometheus-operated.monitoring.svc.cluster.local:9090/prometheus
  alertmanager_url: http://alertmanager-operated.monitoring.svc.cluster.local:9093/alert
  signing_key: { generated-signing-key }
  account_id: { genereted-account-id }
sinksConfig:
- slack_sink:
    name: test_slack
    api_key: { slack-api-key }
    slack_channel: { slack-channel }
enablePlatformPlaybooks: true
runner:
  sendAdditionalTelemetry: true
clusterName: { k8s-cluster-name }