apiVersion: v1
kind: Endpoints
metadata:
  name: external-web-service
  labels:
    apache: external-web
subsets:
  - addresses:
      - ip: 1.2.3.4
    ports:
      - name: http-metric
        port: 9117
        protocol: TCP
#subsets:
#  - addresses:
#  - ip: <gpu-machine-ip>
#ports:
#  - name: metrics
#    port: 9100
#    protocol: TCP