apiVersion: v1
kind: Service
metadata:
  name: external-web-service
  labels:
    apache: external-web
spec:
  type: ExternalName
#  ports:
#    - port: 9117
#      name: http-metric
#      targetPort: 9117
  selector:
    apache: external-web