apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-robusta-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ssh://git@github.com:alstjq8251/devops.git
    targetRevision: HEAD
    path: robusta/robusta
    helm:
      valueFiles:
        - overlays/dev/generated_values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: robusta
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true